version: "3"

# Add the Traefik proxy network, to enable Traefik to access these services
networks:
  public:
    external:
      name: traefik_proxygateway

services:
  app:
    build:
      context: ./
      args:
        - HOST_USER_ID
        - HOST_GROUP_ID
    volumes:
      - ./laravel:/var/www/html
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain this service will respond to
      - "traefik.http.routers.app.rule=Host(`random-qotd.localhost`)"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.app.entrypoints=web"
      # - "traefik.docker.network = traefik_proxygateway"
    networks:
      - public
      - default

  mailhog:
    image: mailhog/mailhog:v1.0.0

  mysql:
    image: mysql:5.7
    env_file: .env
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/etc/mysql
    networks:
      - default

  composer:
    image: composer:1
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    volumes:
      - ./laravel:/var/www/html
    # Run Laravel Composer install
    working_dir: /var/www/html
    command: >
      /bin/sh -c "composer install --no-interaction
      && php composer.post.php"
    labels:
      - "traefik.enable=false"

volumes:
  mysql-data:
  mysql-config:
